export const B = a => b => c => a(b(c))
export const B1 = a => b => c => d => a(b(c)(d))
export const B2 = a => b => c => d => e => a(b(c)(d)(e))
export const B3 = a => b => c => d => a(b(c(d)))
export const C = a => b => c => a(c)(b)
export const C_ = a => b => c => d => a(b)(d)(c)
export const C__ = a => b => c => d => e => a(b)(c)(e)(d)
export const D = a => b => c => d => a(b)(c(d))
export const D1 = a => b => c => d => e => a(b)(c)(d(e))
export const D2 = a => b => c => d => e => a(b(c))(d(e))
export const E = a => b => c => d => e => a(b)(c(d)(e))
export const F = a => b => c => c(b)(a)
export const F_ = a => b => c => d => a(d)(c)(b)
export const F__ = a => b => c => d => e => a(b)(e)(d)(c)
export const G = a => b => c => d => a(d)(b(c))
export const H = a => b => c => a(b)(c)(b)
export const I = a => a
export const I_ = a => b => a(b)
export const I__ = a => b => c => a(b)(c)
export const J = a => b => c => d => a(b)(a(d)(c))
export const K = a => b => a
export const L = a => b => a(b(b))
export const M = a => a(a)
export const M2 = a => b => a(b)(a(b))
export const O = a => b => b(a(b))
export const Q = a => b => c => b(a(c))
export const Q1 = a => b => c => a(c(b))
export const Q2 = a => b => c => b(c(a))
export const Q3 = a => b => c => c(a(b))
export const Q4 = a => b => c => c(b(a))
export const R = a => b => c => b(c)(a)
export const R_ = a => b => c => d => a(c)(d)(b)
export const R__ = a => b => c => d => e => a(b)(d)(e)(c)
export const S = a => b => c => a(c)(b(c))
export const T = a => b => b(a)
export const U = a => b => b(a(a)(b))
export const V = a => b => c => c(a)(b)
export const V_ = a => b => c => d => a(c)(b)(d)
export const V__ = a => b => c => d => e => a(b)(e)(c)(d)
export const W = a => b => a(b)(b)
export const W_ = a => b => c => a(b)(c)(c)
export const W__ = a => b => c => d => a(b)(c)(d)(d)
export const W1 = a => b => b(a)(a)
export const Y = a => (b => b(b))(b => a(c => b(b)(c)))
