"use strict";

module.exports.B = a => b => c => a(b(c))
module.exports.B1 = a => b => c => d => a(b(c)(d))
module.exports.B2 = a => b => c => d => e => a(b(c)(d)(e))
module.exports.B3 = a => b => c => d => a(b(c(d)))
module.exports.C = a => b => c => a(c)(b)
module.exports.C_ = a => b => c => d => a(b)(d)(c)
module.exports.C__ = a => b => c => d => e => a(b)(c)(e)(d)
module.exports.D = a => b => c => d => a(b)(c(d))
module.exports.D1 = a => b => c => d => e => a(b)(c)(d(e))
module.exports.D2 = a => b => c => d => e => a(b(c))(d(e))
module.exports.E = a => b => c => d => e => a(b)(c(d)(e))
module.exports.F = a => b => c => c(b)(a)
module.exports.F_ = a => b => c => d => a(d)(c)(b)
module.exports.F__ = a => b => c => d => e => a(b)(e)(d)(c)
module.exports.G = a => b => c => d => a(d)(b(c))
module.exports.H = a => b => c => a(b)(c)(b)
module.exports.I = a => a
module.exports.I_ = a => b => a(b)
module.exports.I__ = a => b => c => a(b)(c)
module.exports.J = a => b => c => d => a(b)(a(d)(c))
module.exports.K = a => b => a
module.exports.L = a => b => a(b(b))
module.exports.M = a => a(a)
module.exports.M2 = a => b => a(b)(a(b))
module.exports.O = a => b => b(a(b))
module.exports.Q = a => b => c => b(a(c))
module.exports.Q1 = a => b => c => a(c(b))
module.exports.Q2 = a => b => c => b(c(a))
module.exports.Q3 = a => b => c => c(a(b))
module.exports.Q4 = a => b => c => c(b(a))
module.exports.R = a => b => c => b(c)(a)
module.exports.R_ = a => b => c => d => a(c)(d)(b)
module.exports.R__ = a => b => c => d => e => a(b)(d)(e)(c)
module.exports.S = a => b => c => a(c)(b(c))
module.exports.T = a => b => b(a)
module.exports.U = a => b => b(a(a)(b))
module.exports.V = a => b => c => c(a)(b)
module.exports.V_ = a => b => c => d => a(c)(b)(d)
module.exports.V__ = a => b => c => d => e => a(b)(e)(c)(d)
module.exports.W = a => b => a(b)(b)
module.exports.W_ = a => b => c => a(b)(c)(c)
module.exports.W__ = a => b => c => d => a(b)(c)(d)(d)
module.exports.W1 = a => b => b(a)(a)
module.exports.Y = a => (b => b(b))(b => a(c => b(b)(c)))
